language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-gruntfile-yii' ]; then cd .. && eval "mv $currentfolder generator-gruntfile-yii" && cd generator-gruntfile-yii; fi

